### ISSUE TITLE
Run V-Sim-1.0.3 on Window 10

### ISSUE THREAD

**Issue by nhanlee97** [andrescv/V-Sim#1]
Hello Andrés!
I'm very happy when you're developing RISC-V simulation. It's a good notification for human, who researches RISC-V architecture. I downloaded version V-Sim-1.0.3. I had installed Java Runtime Environment (version Java SE 8u192) on Window 10 64-bit before downloading V-Sim-1.0.3, but I haven't still executed the V-Sim-1.0.3. I set up "JRE_HOME" or "JAVA_HOME" variable on "Environment Variable", which not to result my problem. When I compile on Command Prompt window by command "java V-Sim-1.0.3.jar ". It appears an error: "Could not find / or load main class V-Sim-1.0.3.jar ". So you can help me to resolve this problem.
Best regards!
Nhan Le

**Comment by andrescv** [comment]
Hello, very happy to know that you are trying to use V-Sim, sorry about your issue the documentation it's a little bit outdated because I'm currently working in the GUI version of the simulator.  if you are using the jar file you need to this:

`java -jar V-Sim-1.0.3.jar`

you can use all the options also:

`java -jar V-Sim-1.0.3.jar [options] <files>`

Hope this helps you

Best regards!

Andres Castellanos

**Comment by nhanlee97** [comment]
Hello Andrés!
I'm very happy for your response!. Following your feedback, the VSim simulator version 1.0.3 doesn't have the GUI in the present, and you're developing the GUI for VSim (1.0.3). This's an interesting notification for users 👍. So, which version has GUI?. Because I will present homework in front of my class. If VSim simulator has the GUI, it will a good result about the RISC-V architecture discovery.
Thank you, Andrés!
Nhan Le

**Comment by andrescv** [comment]
Hello !

Yes currently the GUI is not present in version 1.0.3, the next release and version **1.1.0** will have this features and fix some known problems with the debugger. I hope this version comes out before the end of the year (it's almost done :smile: ) so I will be very happy if you can present also :crossed_fingers: .

You're welcome :+1:

**Comment by nhanlee97** [comment]
Hi Andrés!
I'm looking forward to "Debut Day of V-Sim simulator version 1.1.0". It's worth to wait 👍. Thanks for your contribution to "RISC-V researching". I will be one of the first to experience version 1.1.0 and if it has problems I will feedback this to you.
Merry Christmas! 🎄 🎅 ⛄️ 🎁  and Happy New Year, Andrés! 🌸 😃 🍷 
Best regards!
Nhan Le.

**Comment by nhanlee97** [comment]
Hi Andrés!
How are you? This's a long time to chat with you. :smiley: So, Have you completed the V-Sim 2.0.0 and this version has GUI?. Sorry, I can't help you build V-Sim version together, because of my less knowledge about java language. :disappointed: Sorry, sorry again. May you know Raspberry become a member of the RISC-V foundation. That's an interesting notice. I hope before next Raspberry version on RISC-V, your tool will become useful simulation for RISC-V beginner. :grinning: 
And, Wish you healthy, Andrés!!!!.
Best regards!
Nhan Le.

**Comment by andrescv** [comment]
Hi Nhan Le!

Hope you're doing great, sorry for taking so long I've been busy last month, thanks for your patience.  I made a new release: **v2.0.0-rc** you can download the JAR file from [here](https://github.com/andrescv/V-Sim/releases). This is a pre-release and the online documentation is not ready yet :disappointed:, but anyways you can still use the simulator because I think is quite intuitive

You can start the GUI with:

```shell
java -jar V-Sim-2.0.0-rc.jar
```
Let met know if you found some problems/issues while using the simulator

Best regards!

**Comment by nhanlee97** [comment]
Hi Andrés!
Ok, Andrés! I got it. I will take some test. If it has problems, I  will notice to you directly. Excuse me, you made this tool with your friend, don't you? If you work in a group, that's an interesting job. 😃

**Comment by andrescv** [comment]
Thanks I will be aware of your news! Btw I sent you an invitation to the V-Sim community to chat [link](https://gitter.im/RISC-V-Sim/community). Yes I work in a group :smile:

**Comment by andrescv** [comment]
I will close this issue, lets continue on gitter
